server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  security:
    permit-all:
      - "/auth/login"
      - "/auth/register"
      - "/public/**"
      - "/actuator/health"
      - "/error"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: "5A7134743777217A25432A462D4A614E645267556B58703272357538782F413F"
    expiration-ms: 86400000 # 24??
    refresh-expiration-ms: 604800000 # 7?

logging:
  level:
    com.example.auth: DEBUG